spring:
  application:
   name: programacionReactivaProyect

  r2dbc:
    url: r2dbc:mysql://localhost:3306/reactiveproyect?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Developer123.

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

openweathermap:
  api:
    key: ${b9cecd47a9f2e6c426920af023db37f2}
    base-url: http://api.openweathermap.org
    timeout: 5000
    max-retries: 3
    rate-limit:
      calls-per-minute: 60